INSERT INTO esami_prescrivibili (id,nome) VALUES (1,'Estrazione di dente deciduo (gratuita fino a 14 anni)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (2,'Estrazione di dente permanente (gratuita fino a 14 anni)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (3,'Altra estrazione chirurgica dente (gratuita fino a 14 anni)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (4,'Ricostruzione dente con otturazione (gratuita fino a 14 anni solo in caso di evento traumatico)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (5,'Ricostruzione dente mediante otturazione a tre o più superfici');
INSERT INTO esami_prescrivibili (id,nome) VALUES (6,'Ricostruzione dente mediante intarsio');
INSERT INTO esami_prescrivibili (id,nome) VALUES (7,'Applicazione di corona');
INSERT INTO esami_prescrivibili (id,nome) VALUES (8,'Applicazione di corona in lega aurea');
INSERT INTO esami_prescrivibili (id,nome) VALUES (9,'Altra applicazione corona');
INSERT INTO esami_prescrivibili (id,nome) VALUES (10,'Applicazione corona e perno');
INSERT INTO esami_prescrivibili (id,nome) VALUES (11,'Altra applicazione corona e perno');
INSERT INTO esami_prescrivibili (id,nome) VALUES (12,'Inserzione di ponte fisso');
INSERT INTO esami_prescrivibili (id,nome) VALUES (13,'Inserzione di protesi rimovibile');
INSERT INTO esami_prescrivibili (id,nome) VALUES (14,'Altra inserzione di protesi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (15,'Inserzione di protesi provvisoria');
INSERT INTO esami_prescrivibili (id,nome) VALUES (16,'Altra riparazione dentaria');
INSERT INTO esami_prescrivibili (id,nome) VALUES (17,'Impianto di dente (gratuita fino a 14 anni)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (18,'Impianto di protesi dentaria');
INSERT INTO esami_prescrivibili (id,nome) VALUES (19,'Terapia canalare in monoradicolato');
INSERT INTO esami_prescrivibili (id,nome) VALUES (20,'Terapia canalare in pluriradicolato');
INSERT INTO esami_prescrivibili (id,nome) VALUES (21,'Apicectomia');
INSERT INTO esami_prescrivibili (id,nome) VALUES (22,'Gengivoplastica');
INSERT INTO esami_prescrivibili (id,nome) VALUES (23,'Asportazione di tessuto della gengiva (gratuita fino a 14 anni)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (24,'Levigatura delle radici');
INSERT INTO esami_prescrivibili (id,nome) VALUES (25,'Intervento chirurgico preprotesico');
INSERT INTO esami_prescrivibili (id,nome) VALUES (26,'Asportazione di lesione dentaria della mandibola (gratuita fino a 14 anni)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (27,'Trattamento ortodontico con apparecchi mobili');
INSERT INTO esami_prescrivibili (id,nome) VALUES (28,'Trattamento con apparecchi fissi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (29,'Trattamento con apparecchi funzionali');
INSERT INTO esami_prescrivibili (id,nome) VALUES (30,'Riparazione di apparecchio ortodontico');
INSERT INTO esami_prescrivibili (id,nome) VALUES (31,'Radiologia diagnostica');
INSERT INTO esami_prescrivibili (id,nome) VALUES (32,'Tomografia computerizzata del rachide');
INSERT INTO esami_prescrivibili (id,nome) VALUES (33,'Tomografia computerizzata con contrasto');
INSERT INTO esami_prescrivibili (id,nome) VALUES (34,'Tomografia computerizzata dell’arto superiore (solo con patologia traumatica acuta)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (35,'Tomografia computerizzata dell’arto superiore senza e con contrasto (patologia o sospetto oncologico)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (36,'Tomografia computerizzata dell’arto inferiore (patologia traumatica)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (37,'Tomografia computerizzata dell’arto inferiore senza e con contrasto (patologia o sospetto oncologico)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (38,'Risonanza magnetica nucleare (RM) della colonna cervicale');
INSERT INTO esami_prescrivibili (id,nome) VALUES (39,'Risonanza magnetica nucleare (RM) della colonna senza e con contrasto');
INSERT INTO esami_prescrivibili (id,nome) VALUES (40,'Risonanza magnetica nucleare (RM) muscoloscheletrica');
INSERT INTO esami_prescrivibili (id,nome) VALUES (41,'Risonanza magnetica nucleare (RM) muscoloscheletrica senza e con contrasto');
INSERT INTO esami_prescrivibili (id,nome) VALUES (42,'Densitometria ossera');
INSERT INTO esami_prescrivibili (id,nome) VALUES (43,'Deossicortisolo');
INSERT INTO esami_prescrivibili (id,nome) VALUES (44,'Acido 5 idrossi 3 indolacetico');
INSERT INTO esami_prescrivibili (id,nome) VALUES (45,'Acido delta');
INSERT INTO esami_prescrivibili (id,nome) VALUES (46,'Ala deidrasi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (47,'Alanina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (48,'Albumina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (49,'Aldolasi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (50,'Alfa amilasi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (51,'Alfa amilasi isoenzimi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (52,'Androstenediolo');
INSERT INTO esami_prescrivibili (id,nome) VALUES (53,'Aspartato aminotrasferiasi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (54,'Calcio totale');
INSERT INTO esami_prescrivibili (id,nome) VALUES (55,'Colesterolo HDL');
INSERT INTO esami_prescrivibili (id,nome) VALUES (56,'Colesterolo LDL');
INSERT INTO esami_prescrivibili (id,nome) VALUES (57,'Colesterolo totale');
INSERT INTO esami_prescrivibili (id,nome) VALUES (58,'Creatinchinasi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (59,'Creatinina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (60,'Cromo');
INSERT INTO esami_prescrivibili (id,nome) VALUES (61,'Enolasi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (62,'Ferro');
INSERT INTO esami_prescrivibili (id,nome) VALUES (63,'Fosfatasi acida');
INSERT INTO esami_prescrivibili (id,nome) VALUES (64,'Fosfatasi alcalina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (65,'Fosfatasi alcalina isoenzima osseo');
INSERT INTO esami_prescrivibili (id,nome) VALUES (66,'Fosfato inorganico');
INSERT INTO esami_prescrivibili (id,nome) VALUES (67,'Lattato');
INSERT INTO esami_prescrivibili (id,nome) VALUES (68,'lipasi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (69,'Magnesio');
INSERT INTO esami_prescrivibili (id,nome) VALUES (70,'Mioglobina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (71,'Potassio');
INSERT INTO esami_prescrivibili (id,nome) VALUES (72,'Proteine');
INSERT INTO esami_prescrivibili (id,nome) VALUES (73,'Sodio');
INSERT INTO esami_prescrivibili (id,nome) VALUES (74,'Sudore');
INSERT INTO esami_prescrivibili (id,nome) VALUES (75,'Trigliceridi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (76,'Urato Urea');
INSERT INTO esami_prescrivibili (id,nome) VALUES (77,'Alfa 2');
INSERT INTO esami_prescrivibili (id,nome) VALUES (78,'Anticorpi anti microsomi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (79,'Antigene carboidratico 125');
INSERT INTO esami_prescrivibili (id,nome) VALUES (80,'Antigene carboidratico15.3');
INSERT INTO esami_prescrivibili (id,nome) VALUES (81,'Antigene carboidratico 19.9');
INSERT INTO esami_prescrivibili (id,nome) VALUES (82,'Antigene carcino embrionario');
INSERT INTO esami_prescrivibili (id,nome) VALUES (83,'Antigeni HLA');
INSERT INTO esami_prescrivibili (id,nome) VALUES (84,'beta tromboglobulina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (85,'cyfra');
INSERT INTO esami_prescrivibili (id,nome) VALUES (86,'Eparina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (87,'Fenotipo RH');
INSERT INTO esami_prescrivibili (id,nome) VALUES (88,'Glicoproteina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (89,'Gruppo sanguigno ABO e RH (D)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (90,'Ige specifiche allergologiche');
INSERT INTO esami_prescrivibili (id,nome) VALUES (91,'Ige specifiche allergologiche screening qualitativo');
INSERT INTO esami_prescrivibili (id,nome) VALUES (92,'Ige specifiche allergologiche');
INSERT INTO esami_prescrivibili (id,nome) VALUES (93,'inibitore attivatore del plasminogeno');
INSERT INTO esami_prescrivibili (id,nome) VALUES (94,'Tempo di protrombina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (95,'Tempo di tromboplastina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (96,'Test aggregazione piastrinica');
INSERT INTO esami_prescrivibili (id,nome) VALUES (97,'Test resistenza proteina C');
INSERT INTO esami_prescrivibili (id,nome) VALUES (98,'Tipizzazione genomica');
INSERT INTO esami_prescrivibili (id,nome) VALUES (99,'Tipizzazione genomica HLA – A sequenziamento diretto');
INSERT INTO esami_prescrivibili (id,nome) VALUES (100,'Tipizzazione genomica HLA – B');
INSERT INTO esami_prescrivibili (id,nome) VALUES (101,'Tipizzazione genomica HLA – B sequenziamento diretto');
INSERT INTO esami_prescrivibili (id,nome) VALUES (102,'Tipizzazione genomica HLA – C');
INSERT INTO esami_prescrivibili (id,nome) VALUES (103,'Tipizzazione genomica HLA – C seq. diretto');
INSERT INTO esami_prescrivibili (id,nome) VALUES (104,'Tipizzazione genomica HLA – DP seq. diretto');
INSERT INTO esami_prescrivibili (id,nome) VALUES (105,'Tipizzazione genomica HLA – DP alta risoluzione');
INSERT INTO esami_prescrivibili (id,nome) VALUES (106,'Tipizzazione genomica HLA – DQ seq. diretto');
INSERT INTO esami_prescrivibili (id,nome) VALUES (107,'Tipizzazione genomica HLA – DQ alta risoluzione');
INSERT INTO esami_prescrivibili (id,nome) VALUES (108,'Tipizzazione genomica HLA – DQB1 bassa risoluzione');
INSERT INTO esami_prescrivibili (id,nome) VALUES (109,'Tipizzazione genomica HLA – DQB1 alta risoluzione');
INSERT INTO esami_prescrivibili (id,nome) VALUES (110,'Tipizzazione genomica HLA – DR seq. diretto');
INSERT INTO esami_prescrivibili (id,nome) VALUES (111,'Tipizzazione genomica HLA – DRB bassa risoluzione');
INSERT INTO esami_prescrivibili (id,nome) VALUES (112,'Tipizzazione genomica HLA – DRB alta risoluzione');
INSERT INTO esami_prescrivibili (id,nome) VALUES (113,'Tipizzazione sierologica HLA classe I');
INSERT INTO esami_prescrivibili (id,nome) VALUES (114,'Tipizzazione sierologica HLA classe II');
INSERT INTO esami_prescrivibili (id,nome) VALUES (115,'Trombossano B2');
INSERT INTO esami_prescrivibili (id,nome) VALUES (116,'Viscosità ematica');
INSERT INTO esami_prescrivibili (id,nome) VALUES (117,'Campylobacter antibiogramma');
INSERT INTO esami_prescrivibili (id,nome) VALUES (118,'Campylobacter da coltura');
INSERT INTO esami_prescrivibili (id,nome) VALUES (119,'Campylobacter esame colturale');
INSERT INTO esami_prescrivibili (id,nome) VALUES (120,'Chlamydie ricerca diretta (EIA)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (121,'Chlamydie ricerca diretta (IF)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (122,'Chlamydie ricerca diretta (ibridazione)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (123,'Miceti anticorpi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (124,'Miceti lieviti');
INSERT INTO esami_prescrivibili (id,nome) VALUES (125,'Salmonelle da coltura');
INSERT INTO esami_prescrivibili (id,nome) VALUES (126,'Shigelle');
INSERT INTO esami_prescrivibili (id,nome) VALUES (127,'Virus epatite B (HBV) Anticorpi Hbeag');
INSERT INTO esami_prescrivibili (id,nome) VALUES (128,'Virus epatite B (HBV) Antigeni Hbeag');
INSERT INTO esami_prescrivibili (id,nome) VALUES (129,'Analisi citogenetica per fragilità cromosomica');
INSERT INTO esami_prescrivibili (id,nome) VALUES (130,'Analisi citogenetica per ricerca siti fragili');
INSERT INTO esami_prescrivibili (id,nome) VALUES (131,'Analisi citogenetica per scambi di cromatidi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (132,'Analisi citogenetica per studio mosaicismo');
INSERT INTO esami_prescrivibili (id,nome) VALUES (133,'Analisi citogenetica per studio riarrangiamenti');
INSERT INTO esami_prescrivibili (id,nome) VALUES (134,'Analisi DNA e ibridazione con sonda');
INSERT INTO esami_prescrivibili (id,nome) VALUES (135,'Analisi DNA per polimorfismo');
INSERT INTO esami_prescrivibili (id,nome) VALUES (136,'Analisi mutazione del DNA con reazione polimerasica a catena');
INSERT INTO esami_prescrivibili (id,nome) VALUES (137,'Analisi mutazione del DNA con ibridazione sonde non radiomarcate');
INSERT INTO esami_prescrivibili (id,nome) VALUES (138,'Analisi mutazione del DNA con ibridazione sonde radiomarcate');
INSERT INTO esami_prescrivibili (id,nome) VALUES (139,'Analisi mutazione del DNA con reverse dot blot');
INSERT INTO esami_prescrivibili (id,nome) VALUES (140,'Analisi di polimorfismi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (141,'Analisi di segmenti di DNA');
INSERT INTO esami_prescrivibili (id,nome) VALUES (142,'Cariotipo ad alta risoluzione');
INSERT INTO esami_prescrivibili (id,nome) VALUES (143,'Cariotipo da metafasi di fibroblasti');
INSERT INTO esami_prescrivibili (id,nome) VALUES (144,'Cariotipo da metafasi linfocitarie');
INSERT INTO esami_prescrivibili (id,nome) VALUES (145,'Cariotipo da metafasi spontanee di villi corali');
INSERT INTO esami_prescrivibili (id,nome) VALUES (146,'Cariotipo da metafasi di midollo osseo');
INSERT INTO esami_prescrivibili (id,nome) VALUES (147,'Colorazione aggiuntiva in bande: Actinomicina D');
INSERT INTO esami_prescrivibili (id,nome) VALUES (148,'Colorazione aggiuntiva in bande: bandeggio C');
INSERT INTO esami_prescrivibili (id,nome) VALUES (149,'Colorazione aggiuntiva in bande: bandeggio G');
INSERT INTO esami_prescrivibili (id,nome) VALUES (150,'Colorazione aggiuntiva in bande: bandeggio G alta ris.');
INSERT INTO esami_prescrivibili (id,nome) VALUES (151,'Colorazione aggiuntiva in bande: bandeggio NOR');
INSERT INTO esami_prescrivibili (id,nome) VALUES (152,'Colorazione aggiuntiva in bande: bandeggio Q');
INSERT INTO esami_prescrivibili (id,nome) VALUES (153,'Colorazione aggiuntiva in bande: bandeggio R');
INSERT INTO esami_prescrivibili (id,nome) VALUES (154,'Colorazione aggiuntiva in bande: bandeggio T');
INSERT INTO esami_prescrivibili (id,nome) VALUES (155,'Colorazione aggiuntiva in bande: distamicina A');
INSERT INTO esami_prescrivibili (id,nome) VALUES (156,'Coltura di amniociti');
INSERT INTO esami_prescrivibili (id,nome) VALUES (157,'Coltura di cellule o tessuti');
INSERT INTO esami_prescrivibili (id,nome) VALUES (158,'Coltura di fibroblasti');
INSERT INTO esami_prescrivibili (id,nome) VALUES (159,'Coltura di linee cellulari stabilizzate con virus');
INSERT INTO esami_prescrivibili (id,nome) VALUES (160,'Coltura di linee linfocitarie stabilizzate con virus o interleuchina');
INSERT INTO esami_prescrivibili (id,nome) VALUES (161,'Coltura di linfociti fetali');
INSERT INTO esami_prescrivibili (id,nome) VALUES (162,'Coltura di linfociti periferici');
INSERT INTO esami_prescrivibili (id,nome) VALUES (163,'Coltura di materiale abortivo');
INSERT INTO esami_prescrivibili (id,nome) VALUES (164,'Coltura semisolida di cellule emopoietiche');
INSERT INTO esami_prescrivibili (id,nome) VALUES (165,'Coltura di villi coriali a breve termine');
INSERT INTO esami_prescrivibili (id,nome) VALUES (166,'Coltura di cilli coriali');
INSERT INTO esami_prescrivibili (id,nome) VALUES (167,'Coltura per studio del cromosoma X');
INSERT INTO esami_prescrivibili (id,nome) VALUES (168,'Conservazione campioni DNA RNA');
INSERT INTO esami_prescrivibili (id,nome) VALUES (169,'Crioconservazione in azoto liquido di colture cellulari');
INSERT INTO esami_prescrivibili (id,nome) VALUES (170,'Crioconservazione in azoto liquido di cellule e tessuti');
INSERT INTO esami_prescrivibili (id,nome) VALUES (171,'Digestione DNA con enzimi');
INSERT INTO esami_prescrivibili (id,nome) VALUES (172,'Estrazione DNA o RNA');
INSERT INTO esami_prescrivibili (id,nome) VALUES (173,'Ibridazione con sonda molecolare');
INSERT INTO esami_prescrivibili (id,nome) VALUES (174,'Ibridazione in SITU (Fish)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (175,'Ricerca Mutazione (DGGE)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (176,'Ricerca mutazione (SSCP)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (177,'Analisi DNA studio citometrico');
INSERT INTO esami_prescrivibili (id,nome) VALUES (178,'Orticarie fisiche');
INSERT INTO esami_prescrivibili (id,nome) VALUES (179,'Inalanti');
INSERT INTO esami_prescrivibili (id,nome) VALUES (180,'Test epicutanei a lettura ritardata');
INSERT INTO esami_prescrivibili (id,nome) VALUES (181,'Test a lettura immediata');
INSERT INTO esami_prescrivibili (id,nome) VALUES (182,'Tomoscintigrafia miocardica (PET)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (183,'Tomoscintigrafia Cerebrale (PET)');
INSERT INTO esami_prescrivibili (id,nome) VALUES (184,'Radioterapia stereotassica');
INSERT INTO esami_prescrivibili (id,nome) VALUES (185,'Irradiazione cutanea');
INSERT INTO esami_prescrivibili (id,nome) VALUES (186,'Terapie e riabilitazioni');
INSERT INTO esami_prescrivibili (id,nome) VALUES (187,'Esercizi respiratori per seduta collettiva');
INSERT INTO esami_prescrivibili (id,nome) VALUES (188,'Esercizi respiratori per seduta individuale');
INSERT INTO esami_prescrivibili (id,nome) VALUES (189,'Tomoscintigrafia globale');
INSERT INTO esami_prescrivibili (id,nome) VALUES (190,'Irradiazione cutanea');
INSERT INTO esami_prescrivibili (id,nome) VALUES (191,'Terapia del dolore da metastasi ossee');
INSERT INTO esami_prescrivibili (id,nome) VALUES (192,'Ablazione tartaro');
INSERT INTO esami_prescrivibili (id,nome) VALUES (193,'Sigillatura solchi e fossette');
INSERT INTO esami_prescrivibili (id,nome) VALUES (194,'Rimozione protesi dentarie');
INSERT INTO esami_prescrivibili (id,nome) VALUES (195,'Immunizzazione allergia');
INSERT INTO esami_prescrivibili (id,nome) VALUES (196,'Immunizzazione malattia autoimmune');
INSERT INTO esami_prescrivibili (id,nome) VALUES (197,'Terapia luce ultravioletta');
INSERT INTO esami_prescrivibili (id,nome) VALUES (198,'Splintaggio per gruppi di 4 denti');
INSERT INTO esami_prescrivibili (id,nome) VALUES (199,'Trattamento applicazioni protesi semovibili');