INSERT INTO visite_specialistiche (id,nome) VALUES (1,'Ambulatorio infermieristico');
INSERT INTO visite_specialistiche (id,nome) VALUES (2,'Colloquio psicologico clinico');
INSERT INTO visite_specialistiche (id,nome) VALUES (3,'Consigli per adattamento a perdita di vista, uso di aiuti per bassa vista');
INSERT INTO visite_specialistiche (id,nome) VALUES (4,'Consulenza anatomopatologica per revisione diagnostica di preparati allestiti in altra sede (prescrivibile una sola volta per lo stesso episodio patologico)');
INSERT INTO visite_specialistiche (id,nome) VALUES (5,'Consultorio');
INSERT INTO visite_specialistiche (id,nome) VALUES (6,'Controllo e programmazione pace-maker');
INSERT INTO visite_specialistiche (id,nome) VALUES (7,'Controllo periodico per terapia anticoagulante orale (TAO)');
INSERT INTO visite_specialistiche (id,nome) VALUES (8,'Controllo protesico elettroacustico');
INSERT INTO visite_specialistiche (id,nome) VALUES (9,'Controllo/programmazione di neurostimolatore encefalico');
INSERT INTO visite_specialistiche (id,nome) VALUES (10,'Controllo/programmazione di neurostimolatore spinale');
INSERT INTO visite_specialistiche (id,nome) VALUES (11,'Medico di guardia ostetrico h24');
INSERT INTO visite_specialistiche (id,nome) VALUES (12,'Messa a punto e fornitura di occhiali');
INSERT INTO visite_specialistiche (id,nome) VALUES (13,'Plicometria, valutazione dello stato nutrizionale');
INSERT INTO visite_specialistiche (id,nome) VALUES (14,'Prescrizione, messa a punto e fornitura di lenti a contatto');
INSERT INTO visite_specialistiche (id,nome) VALUES (15,'Relazione per organi giudiziari');
INSERT INTO visite_specialistiche (id,nome) VALUES (16,'Stesura del piano di emodialisi o di dialisi peritoneale');
INSERT INTO visite_specialistiche (id,nome) VALUES (17,'Visita allergologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (18,'Visita allergologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (19,'Visita anestesiologica/algologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (20,'Visita anestesiologica/algologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (21,'Visita angiologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (22,'Visita angiologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (23,'Visita audiologica, visita foniatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (24,'Visita cardiochirurgica');
INSERT INTO visite_specialistiche (id,nome) VALUES (25,'Visita cardiochirurgica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (26,'Visita cardiochirurgica pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (27,'Visita cardiochirurgica pediatrica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (28,'Visita cardiologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (29,'Visita cardiologica. Incluso: ECG');
INSERT INTO visite_specialistiche (id,nome) VALUES (30,'Visita chirurgia di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (31,'Visita chirurgia generale');
INSERT INTO visite_specialistiche (id,nome) VALUES (32,'Visita chirurgia maxillo facciale');
INSERT INTO visite_specialistiche (id,nome) VALUES (33,'Visita chirurgia maxillo facciale di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (34,'Visita chirurgia pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (35,'Visita chirurgia pediatrica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (36,'Visita chirurgia plastica');
INSERT INTO visite_specialistiche (id,nome) VALUES (37,'Visita chirurgia plastica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (38,'Visita chirurgia toracica');
INSERT INTO visite_specialistiche (id,nome) VALUES (39,'Visita chirurgia toracica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (40,'Visita chirurgia vascolare');
INSERT INTO visite_specialistiche (id,nome) VALUES (41,'Visita chirurgia vascolare di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (42,'Visita dentistica - odontostomatologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (43,'Visita dentistica - odontostomatologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (44,'Visita dentistica - odontostomatologica pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (45,'Visita dermatologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (46,'Visita dermatologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (47,'Visita di medicina estetica');
INSERT INTO visite_specialistiche (id,nome) VALUES (48,'Visita di medicina estetica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (49,'Visita di medicina fisica e riabilitazione');
INSERT INTO visite_specialistiche (id,nome) VALUES (50,'Visita di medicina fisica e riabilitazione di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (51,'Visita di medicina nucleare');
INSERT INTO visite_specialistiche (id,nome) VALUES (52,'Visita di medicina nucleare di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (53,'Visita di radiologia interventistica');
INSERT INTO visite_specialistiche (id,nome) VALUES (54,'Visita di radiologia interventistica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (55,'Visita di radioterapia');
INSERT INTO visite_specialistiche (id,nome) VALUES (56,'Visita di riabilitazione neurologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (57,'Visita di riabilitazione neurologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (58,'Visita dietologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (59,'Visita dietologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (60,'Visita ematologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (61,'Visita ematologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (62,'Visita endocrinologica e diabetologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (63,'Visita endocrinologica e diabetologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (64,'Visita endocrinologica pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (65,'Visita epatologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (66,'Visita epatologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (67,'Visita fisiatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (68,'Visita fisiatrica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (69,'Visita gastroenterologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (70,'Visita gastroenterologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (71,'Visita genetica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (72,'Visita genetica medica');
INSERT INTO visite_specialistiche (id,nome) VALUES (73,'Visita geriatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (74,'Visita geriatrica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (75,'Visita ginecologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (76,'Visita ginecologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (77,'Visita immunologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (78,'Visita Immunologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (79,'Visita infettivologica o delle malattie tropicali');
INSERT INTO visite_specialistiche (id,nome) VALUES (80,'Visita infettivologica o delle malattie tropicali di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (81,'Visita medicina generale / assistenza primaria / servizio di continuità assistenziale');
INSERT INTO visite_specialistiche (id,nome) VALUES (82,'Visita medicina generale / assistenza primaria / servizio di continuità assistenziale di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (83,'Visita medico-sportiva');
INSERT INTO visite_specialistiche (id,nome) VALUES (84,'Visita medico-sportiva di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (85,'Visita multidisciplinare');
INSERT INTO visite_specialistiche (id,nome) VALUES (86,'Visita multidisciplinare per cure palliative');
INSERT INTO visite_specialistiche (id,nome) VALUES (87,'Visita nefrologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (88,'Visita nefrologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (89,'Visita nefrologica pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (90,'Visita nefrologica pediatrica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (91,'Visita neurochirurgica');
INSERT INTO visite_specialistiche (id,nome) VALUES (92,'Visita neurochirurgica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (93,'Visita neurochirurgica pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (94,'Visita neurologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (95,'Visita neurologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (96,'Visita neurologica pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (97,'Visita neuropsichiatrica infantile');
INSERT INTO visite_specialistiche (id,nome) VALUES (98,'Visita neuropsichiatrica infantile di controlloVisita oculistica');
INSERT INTO visite_specialistiche (id,nome) VALUES (99,'Visita oculistica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (100,'Visita oculistica pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (101,'Visita oncoematologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (102,'Visita oncoematologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (103,'Visita oncoematologica pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (104,'Visita oncoematologica pediatrica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (105,'Visita oncologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (106,'Visita oncologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (107,'Visita ortopedica');
INSERT INTO visite_specialistiche (id,nome) VALUES (108,'Visita ortopedica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (109,'Visita ostetrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (110,'Visita ostetrica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (111,'Visita otorinolaringoiatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (112,'Visita otorinolaringoiatrica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (113,'Visita pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (114,'Visita per cure palliative di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (115,'Visita pneumologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (116,'Visita pneumologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (117,'Visita procreazione (fecondazione) assistita');
INSERT INTO visite_specialistiche (id,nome) VALUES (118,'Visita proctologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (119,'Visita proctologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (120,'Visita psichiatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (121,'Visita psichiatrica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (122,'Visita psicodiagnostica');
INSERT INTO visite_specialistiche (id,nome) VALUES (123,'Visita radioterapica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (124,'Visita reumatologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (125,'Visita reumatologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (126,'Visita senologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (127,'Visita senologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (128,'Visita urologica pediatrica');
INSERT INTO visite_specialistiche (id,nome) VALUES (129,'Visita urologica pediatrica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (130,'Visita urologica/andrologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (131,'Visita urologica/andrologica di controllo');
INSERT INTO visite_specialistiche (id,nome) VALUES (132,'Visita vulnologica');
INSERT INTO visite_specialistiche (id,nome) VALUES (133,'Visita vulnologica di controllo');
